name: 'Echo JSON'
description: 'Echo your json'
inputs:
  i-say:
    description: 'What do you say?'
    required: true
    default: '{}'
outputs:
  return-json:
    description: 'return json you said'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.i-say }}
