on: [push]

jobs:
  echo-job:
    runs-on: ubuntu-latest
    name: run-local-action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run
        uses: ./
        id: echo-json-action
        with:
          i-say: '{"a": 1234}'
      - name: Show return-json
        run: echo "Returned ${{ steps.echo-json-action.outputs.return-json }}"
